### ISSUE TITLE
[Bug]: 突然出现了很奇怪的bug

### ISSUE THREAD

**Issue by wopanda** [Quorafind/Obsidian-Thino#539]
### Bug Description | BUG 描述

app.js:1 Uncaught (in promise) Error: Invalid value `function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }` for setting `options.showPreview`
    at e.exports [as setOptions] (app.js:1:197995)
    at c (app.js:1:196079)
    at Mx (app.js:1:847706)
    at t.render (app.js:1:1296392)
    at eval (plugin:obsidian-memos:193:7942)
    at eval (plugin:obsidian-memos:193:8496)
    at ed (plugin:obsidian-memos:171:24537)
    at Xs (plugin:obsidian-memos:171:42968)
    at fy (plugin:obsidian-memos:171:37056)
    at _s (plugin:obsidian-memos:169:3272)
    at pw (plugin:obsidian-memos:171:41788)
    at Vl (plugin:obsidian-memos:171:40780)
    at dy (plugin:obsidian-memos:171:36166)
    at _ (plugin:obsidian-memos:164:16716)
    at Immediate.Q (plugin:obsidian-memos:164:17094)
    at process.processImmediate (node:internal/timers:476:21)

### Relevant Screenshot | 相关截图

![image](https://github.com/Quorafind/Obsidian-Thino/assets/61578085/36016457-9e10-48df-aa5c-36e5504a82f5)

### Obsidian Version | Obsidian 版本

v1.5.12

### Which editor are you using? (If applicable)

- [X] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
已经初步判断问题后续更新对应版本即可

**Comment by juestchaos** [comment]
更新到 canvas mindmap 插件到最新版本后后续版本即可：https://github.com/Quorafind/Obsidian-Canvas-MindMap/releases/tag/0.1.10
