### ISSUE TITLE
[Question]:  ""打开失败

### ISSUE THREAD

**Issue by 767251930** [Quorafind/Obsidian-Thino#728]
### Bug Description | BUG 描述

在只开启Thino插件的情况下，在发布的Thino内容后，在有Thino界面和相关日记都打开的情况下，重新打开obsidian，会有  “”打开失败的报错

obsidian调试报错如下：

app.js:1 TypeError: Cannot read properties of null (reading 'listSelections')
    at t.findActiveHeading (app.js:1:2813633)
    at t.update (app.js:1:2815621)
    at t.<anonymous> (app.js:1:1377584)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at v (app.js:1:235994)
    at t.onLoadFile (app.js:1:1377511)
    at t.<anonymous> (app.js:1:1375373)
（匿名） @ app.js:1
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'listSelections')
    at t.findActiveHeading (app.js:1:2813633)
    at t.update (app.js:1:2815621)
    at l (app.js:1:518110)
    at c (app.js:1:518226)

### Relevant Screenshot | 相关截图

![image](https://github.com/user-attachments/assets/81a6430e-b210-49e5-9178-ddb877c32691)

![image](https://github.com/user-attachments/assets/c05d70d2-7a97-4264-ad0d-b0629b2e9be1)

### Obsidian Version | Obsidian 版本

1.7.4

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
控制台的报错不像是 thino 的
你能提供更多辅助信息吗
比如你的thino 开启的是何种模式，日记，单文件，或者其他， 默认存储模式又是什么
日记插件如何配置的

你也可以在 pkmer 群里，联系 pkmer 的管理员

**Comment by iamyourgod** [comment]
![image](https://github.com/user-attachments/assets/8a2526d4-679b-400a-ba98-e882d96e8d0b)
一样的问题，插件不能用了

**Comment by juestchaos** [comment]
> > Bot detected the issue body's language is not English, translate it automatically...
> 
> ![image](https://private-user-images.githubusercontent.com/19583938/381849281-8a2526d4-679b-400a-ba98-e882d96e8d0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDYyNTQsIm5iZiI6MTczMDU0NTk1NCwicGF0aCI6Ii8xOTU4MzkzOC8zODE4NDkyODEtOGEyNTI2ZDQtNjc5Yi00MDBhLWJhOTgtZTg4MmQ5NmU4ZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDExMTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDlhZTUzNTlkYTRmNTA4Nzg5NjNlNGFlMmNjNTRmZDYxMDRiYjZlNGI2MGMzZWMxYmJmODRiMjkzYTUzOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yDMl7fMOH-PFKy92635cJQNdmOSLhqYlRieT96RR7x8) Same problem, the plug-in doesn't work anymore

你的截图中都不是 thino 的报错，而是其他插件
尽量描述的你的配置情况，比如你存储什么模式，默认用什么什么模式，日记或单文件，如果是日记，配置是什么

**Comment by juestchaos** [comment]
目前看来，已经通过远程查看配置的同学，并不是 thino 问题导致的，而是因为 obsidian 的安装版本过低。
目前此 issue 没有得到进一步信息，相关同学，可以先升级下自己  obsidian 安装版本

**Comment by JDIalice** [comment]
我也出现了一样的问题，请问你解决了吗

<img width="541" alt="Image" src="https://github.com/user-attachments/assets/5f18b726-b3f2-4c1a-81cb-c476b19028ff" />

**Comment by juestchaos** [comment]
@JDIalice 安装 obsidian 1.8.4 而不是直接升级

**Comment by JDIalice** [comment]
@juestchaos 感谢，重装ob1.8.4后好了，虽然不知道为什么不能直接升级，但是问题已解决

**Comment by syu-id** [comment]
我重装 1.8.4 后依然有这个错误

![Image](https://github.com/user-attachments/assets/a7ffcd15-b7e0-42e8-bbfc-e24abacb2832)

**Comment by juestchaos** [comment]
我看这个提示很眼熟，请检查下是否安装了 iconize 插件，并升级到最新版
